name:                pconv
version:             0.1.0.0
github:              "ravensiris/pconv"
license:             BSD3
author:              "Raven's Iris"
maintainer:          "ravens.iris.mx@gmail.com"
copyright:           "2020 Raven's Iris"

extra-source-files:
- README.org

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/ravensiris/pconv#readme>

dependencies:
- base >= 4.7 && < 5
- text
- aeson
- req
- bytestring
- http-client
- unicode-show

library:
  source-dirs: src

executables:
  pconv-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - pconv

# tests:
#   pconv-test:
#     main:                Spec.hs
#     source-dirs:         test
#     ghc-options:
#     - -threaded
#     - -rtsopts
#     - -with-rtsopts=-N
#     dependencies:
#     - pconv
